### ISSUE TITLE
Error writing log file during initial execution

### ISSUE THREAD

**Issue by bharathc02** [email2vimalraj/nightwatch-test#1]
**Issue:**

During test exection, I'm getting the error 
`Error writing log file to: /*****/nightwatch-test/logs/selenium-debug.log`

**Steps:**
1. Clone the project
2. Run `npm install`
3. Run `npm run test`
4. There is no logs folder created by default.
5. Browsers are spawned and tests run. In the end of execution, the error `Error writing log file to: /*****/nightwatch-test/logs/selenium-debug.log` is thrown.
6. If `logs` is created manually, the log file is written.

Nightwatch json config has an entry for [logs](https://github.com/email2vimalraj/nightwatch-test/blob/master/nightwatch.json#L11). 

**Solution:**
Either commit empty logs folder or create the folder if it is not present.

**Comment by email2vimalraj** [comment]
Fixed by removing the dependency of the `logs` folder. Now the log files are generated in the root directory.

Feel free to re-open if in case further details required.

**Comment by bharathc02** [comment]
Verified
